version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=80
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
