version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
    restart: always
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/nginx-entrypoint.sh
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - app
    environment:
      - PORT=${PORT}
    restart: always
    entrypoint: /bin/bash -c 'chmod +x /docker-entrypoint.d/nginx-entrypoint.sh && /docker-entrypoint.sh nginx -g "daemon off;"'
    

